'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Photon.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property book_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("book_ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property data_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("data_ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Public Function nCk(N, K)
        '''results = 1
        '''For i = 1 to K
        '''results = results * (N - (K - i))
        '''results = results / i
        '''Next
        '''nCk = results
        '''End Function
        '''
        '''Public Function nPk(N, K)
        '''results = 1
        '''For i = (N - K) + 1 to N
        '''results = results * i
        '''Next
        '''nPk = results
        '''End Function
        '''
        '''Public Function iAdd(re1, im1, re2, im2)
        '''iAdd = (re1 + re2) &amp; &quot; + &quot; &amp; (im1 + im2) &amp; &quot; i&quot;
        '''End Function
        '''
        '''Public Function iSub(re1, im1, re2, im2)
        '''iSub = (re1 - re2) &amp; &quot; + &quot; &amp; (im1 - im2) &amp; &quot; i&quot;
        '''End Function
        '''
        '''Public Function iMult [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Functions() As String
            Get
                Return ResourceManager.GetString("Functions", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gear_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gear_ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; ?&gt;
        '''&lt;grammar version=&quot;1.0&quot; xml:lang=&quot;en-US&quot; mode=&quot;voice&quot; root=&quot;topLevel&quot;
        '''xmlns=&quot;http://www.w3.org/2001/06/grammar&quot; tag-format=&quot;semantics/1.0&quot;&gt;
        '''  &lt;rule id=&quot;topLevel&quot;&gt;
        '''    &lt;one-of&gt;
        '''      &lt;item&gt; &lt;ruleref uri=&quot;#symbol&quot;/&gt; &lt;/item&gt;
        '''      &lt;item&gt; data &lt;/item&gt;
        '''      &lt;item&gt; matrix &lt;/item&gt;
        '''      &lt;item&gt; &lt;ruleref uri=&quot;#togglefractionmode&quot;/&gt; &lt;/item&gt;
        '''      &lt;item&gt; &lt;ruleref uri=&quot;#toggleradianmode&quot;/&gt; &lt;/item&gt;
        '''      &lt;item&gt; clear &lt;/item&gt;
        '''      &lt;item&gt; go &lt;/item&gt;
        '''	  &lt;item&gt; cancel &lt;/i [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property grammar() As String
            Get
                Return ResourceManager.GetString("grammar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property graph_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("graph_ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property matrix_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("matrix_ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Microphone_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Microphone_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property P_Transparent() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("P_Transparent", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scale_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scale_ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property table_ico() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("table_ico", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
